from custom_envs.envs.centipede_env_v2 import CentipedeEnv_v2
from custom_envs.envs.centipede_env import CentipedeEnv
from custom_envs.envs.humanoid_v4 import HumanoidEnv_v4
from custom_envs.envs.humanoid_v3 import HumanoidEnv_v3
from custom_envs.envs.humanoid_v2 import HumanoidEnv_v2
from custom_envs.envs.humanoid import HumanoidEnv
from custom_envs.envs.leg_model import HumanoidLegEnv
from custom_envs.envs.dog_env import DogEnv
from custom_envs.envs.dog_env_v2 import DogEnv_v2
from custom_envs.envs.dog_env_v3 import DogEnv_v3
from custom_envs.envs.cheetah_env import HalfCheetahEnv
from custom_envs.envs.dog_2_env import Dog2Env
from custom_envs.envs.dog_2_env_v2 import Dog2Env_v2
from custom_envs.envs.centipede8_env_v2 import Centipede8Env_v2
from custom_envs.envs.dog8_2_env import Dog8_2Env
from custom_envs.envs.dog8_2_env_v2 import Dog8_2Env_v2
from custom_envs.envs.dog18_2_env import Dog18_2Env
from custom_envs.envs.dog18_2_env_v2 import Dog18_2Env_v2
from custom_envs.envs.centipede4_2_env import Centipede4_2Env
from custom_envs.envs.centipede4_2_env_v2 import Centipede4_2Env_v2